### ISSUE TITLE
PR to extend `formatNote()`?

### ISSUE THREAD

**Issue by rossellhayes** [egenn/music#1]
Hi there, I'm a big fan of your package! I was wondering if you'd be interested in a PR that would add some additional functionality to `formatNote()`. In particular, I've noticed that `formatNote()` doesn't support double sharps or Unicode music characters. Please let me know if a PR would be appreciated!

**Comment by egenn** [comment]
Hi - that sounds great, feel free to submit a PR.
Thank you!
